[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# API redirects - must come before SPA fallback
[[redirects]]
  from = "/api/auth/discord/token"
  to = "/.netlify/functions/auth-discord-token"
  status = 200
  force = true

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200
  force = true

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 